// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mbmhggxdpabvwyqwfmrv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1ibWhnZ3hkcGFidnd5cXdmbXJ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjExNTg3NTQsImV4cCI6MjA3NjczNDc1NH0.ZpfJl0iocR5QcZosuG-F7wx9ZaMZzooSfuwPGIKz77M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});